<?php
function real_angular_menu() {
    $items = array();
    $items['home_search'] = array(
        'title' => t('Home Search'),
        'page callback' => 'real_angular_search',
        'access arguments' => array('access content'),
    );


    return $items;
}
function real_angular_theme() {
    $themes = array();
    $themes['real_angular'] = array(
        'template' => 'themes/real_angular',
        'parameters' => array(),
    );
    return $themes;
}
function real_angular_search() {
    angularjs_init_application('real_angular');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/misc/lodash.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/misc/angular-google-maps.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/misc/angular-simple-logger.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/controller/retsMap.controller.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/controller/infoWindow.controller.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/directives/retsSearchForm.directive.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/directives/retsSearchResults.directive.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/services/retsAPI.service.js');
    drupal_add_js(drupal_get_path('module', 'real_angular') . '/js/app.js');

    return theme('real_angular');
}

function real_angular_display() {

    return drupal_get_form('real_angular_form');
}
function real_angular_form($form, &$form_state) {
    $form['L_ListingID'] = array(
        '#type' => 'textfield',
        '#title' => 'MLS Number',
        '#attributes' => array(
            'ng-change' => array('retsFormChange()'),
            'ng-model' => array('form.L_ListingID')
        )
    );
    $form['L_Keyword2'] = array(
        '#type' => 'textfield',
        '#title' => 'Beds',
        '#attributes' => array(
            'ng-change' => array('retsFormChange()'),
            'ng-model' => array('form.L_Keyword2')
        )
    );
//    $form['retsSearchMarkup'] = array(
//        '#type' => 'item',
//        '#ng_controller' => 'RetsSearchCtrl',
//        '#markup' => '<div rets-search-form>Majellin!</div>'
//    );
//    $form['submit'] = array(
//        '#type' => 'submit',
//        '#value' => 'Submit that shit!'
//    );
    return $form;
}