<?php

function real_blocks_block_info() {
  $blocks = array();
  $blocks['least_expensive'] = array(
    'info' => t('Least Expensive Block'),
  );

  return $blocks;
}

function real_blocks_block_view($delta='') {
  $block = array();
  if($delta == 'least_expensive') {

    $listings = file_get_contents('http://rets.mindimage.net/mls.php?action=least_expensive');


    $block['subject'] = t('Least Expensive Listings');
    $block['content'] = theme('real_blocks', [
      'listings'=> $listings,
    ]);
  }
  return $block;
}
function real_blocks_theme() {
  $theme = array();
  $theme['real_blocks'] = array(
    'template' => 'templates/least_expensive',
  );
  return $theme;
}

