<?php

function real_blocks_block_info() {
  $blocks = array();
  $blocks['least_expensive'] = array(
    'info' => t('Least Expensive Block'),
  );

  return $blocks;
}

function real_blocks_block_view($delta='') {
  $block = array();
  if($delta == 'least_expensive') {


    $block['subject'] = t('Least Expensive Listings');
    $block['content'] = array(
      '#theme' => 'real_blocks',
    );
  }
  return $block;
}

function real_blocks_theme() {
  module_load_include('inc', 'real_blocks', 'includes/real_listings_db');
  var_dump($link);
  $theme = array();
  $theme['real_blocks'] = array(
    'template' => 'templates/least_expensive',
    'variables' => array(),
  );
  return $theme;
}
